# Generated by Django 3.0.7 on 2020-06-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='racer/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Гонщики и руководители',
                'verbose_name_plural': 'Гонщики и руководители',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Опмсание')),
                ('logo', models.ImageField(upload_to='teams/', verbose_name='Логотип')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год дебюта')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('base', models.CharField(max_length=50, verbose_name='База')),
                ('total_victories', models.PositiveSmallIntegerField(default=0, verbose_name='Всего побед')),
                ('total_points', models.PositiveSmallIntegerField(default=0, verbose_name='Всего очков')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('category', models.ManyToManyField(related_name='team_category', to='teams.Category', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='team_director', to='teams.Racer', verbose_name='руководитель')),
                ('racers', models.ManyToManyField(related_name='team_racer', to='teams.Racer', verbose_name='гонщики')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TeamShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='team_shots/', verbose_name='Изображение')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Фотография команды',
                'verbose_name_plural': 'Фотографии каманды',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Reviews', verbose_name='Родитель')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
